remove dupe variable type
nexient-llc/tf-aws-module_primitive-dns_zone pull request #3
Opened 2024-01-17 19:31 UTC by nexient-ajoshi

2024-01-22 20:35 UTC, nexient-ajoshi commented
Terratests need to be fixed. Before making module public, as part of separate PR those will be added.

2024-01-22 20:55 UTC, dsahoo-nexient requested changes

2024-01-22 20:55 UTC, dsahoo-nexient commented on main.tf
>  module "zone" {
As per our earlier discussions today, this should first be a primitive module and then we can refer from a collection module

2024-01-23 16:50 UTC, nexient-ajoshi commented on main.tf
>  module "zone" {
I ended up renaming this module. This module is a primitive by itself. It allows to create DNS zones. To create DNS zone records there is separate module.

2024-01-23 17:05 UTC, dsahoo-nexient requested changes

2024-01-23 17:05 UTC, dsahoo-nexient commented on outputs.tf
> +output "route53_zone_zone_ids" {
Name and the description doesn't match. name is plural and description is singular. Is it going to return multiple IDs or single ID?

2024-01-23 17:05 UTC, dsahoo-nexient commented on examples/private_zone/outputs.tf
> +output "route53_zone_zone_ids" {
same comment as others. description and name doesnt match for all the outputs

2024-01-23 17:05 UTC, dsahoo-nexient commented on examples/public_zone/outputs.tf
> +output "route53_zone_zone_ids" {
name and description doesnt match

2024-01-23 22:31 UTC, chris-taylor-ntt commented on examples/private_zone/.terraform.lock.hcl
This file is in the .gitignore:

```
# We don't want to commit the test run lock files
.terraform.lock.hcl
```

However, it was probably added to the repo in the same commit as the .gitignore, so it wouldn't have been excluded and now just accumulates changes. Could you remove it from your commit?

2024-01-23 22:31 UTC, chris-taylor-ntt commented on examples/private_zone/locals.tf
> +    for idx, v in var.zones : idx => {
Minor nitpick, but there's a discrepancy between this for loop and the one above it. Above, the map's key is denoted as `k` but here (and below) it's `idx`.

I don't have a strongly-held opinion when it comes to using `idx` or `k` (just a loose preference for `k` given we also have `v`), but I would like to ensure that we're internally consistent both within this file and across the rest of the module. The other example's `locals.tf` has this same issue.

2024-01-23 22:31 UTC, chris-taylor-ntt commented on variables.tf
> +# Variables required by the dnz zone module
```suggestion
# Variables required by the DNS zone module
```

2024-01-24 14:31 UTC, nexient-ajoshi commented on examples/private_zone/locals.tf
> +    for idx, v in var.zones : idx => {
@chris-taylor-ntt  Thanks Chris!! Fixed it

2024-01-24 14:32 UTC, nexient-ajoshi commented on examples/private_zone/.terraform.lock.hcl
Thanks @chris-taylor-ntt 
Removed it!!

2024-01-24 14:51 UTC, chris-taylor-ntt approved these changes

2024-01-24 17:46 UTC, merged